### PR TITLE
fix: load 8 bit on mutliple GPUs

### PR DESCRIPTION
**Pull request by exander77**

### CODE REVIEW

**Comment by orangetin** [comment]
Thanks! This looks good, I'm going to test it and merge soon

**Comment by orangetin** [comment]
Hey @exander77 , could you remove the stuff with the pre-prompt from your PR? It looks good and I'd recommend opening a new PR in the main repo adding those changes.

**Comment by exander77** [comment]
> Hey @exander77 , could you remove the stuff with the pre-prompt from your PR? It looks good and I'd recommend opening a new PR in the main repo adding those pre-prompt changes.

Done.

**Comment by orangetin** [comment]
Thanks! You should make a new PR for the pre-prompt at the main repo. 

I'm testing your commit right now and it looks like load-in-8bit works with dtype float16. It turns out that the error (when running 8-bit with max_memory) comes from the fact that 8-bit cannot be stored on the CPU. 

I was able to fix this by re-doing the entire __init__ function to:
```
def __init__(self, model_name, gpu_id, max_memory, load_in_8bit):
      device = torch.device('cuda', gpu_id)   # TODO: allow sending to cpu
      quantization_config = BitsAndBytesConfig(
          load_in_8bit=load_in_8bit, 
          llm_int8_enable_fp32_cpu_offload=True,
      )   # config to load in 8-bit if load_in_8bit

      # recommended default for devices with > 40 GB VRAM
      # load model onto one device
      if max_memory is None:
          device_map="auto"
      else:
          config = AutoConfig.from_pretrained(model_name)
          # load empty weights
          with init_empty_weights():
              model_from_conf = AutoModelForCausalLM.from_config(config)

          model_from_conf.tie_weights()

          #create a device_map from max_memory
          device_map = infer_auto_device_map(
              model_from_conf,
              max_memory=max_memory,
              no_split_module_classes=["GPTNeoXLayer"],
              dtype="float16",
          )

      self._model = AutoModelForCausalLM.from_pretrained(
          model_name, 
          torch_dtype=torch.float16, 
          device_map=device_map, 
          offload_folder="offload",
          quantization_config=quantization_config,
      )
      if not load_in_8bit:
          self._model.to(device) 

```

**Pull request closed without merging**
